#!/bin/sh

chmod +x /etc/init.d/3ginfo_ttl 2>/dev/null

uci -q batch << EOF
	delete firewall.3ginfo_ttl
	set firewall.3ginfo_ttl=include
	set firewall.3ginfo_ttl.type=script
	set firewall.3ginfo_ttl.path=/etc/firewall.d/3ginfo_ttl
	set firewall.3ginfo_ttl.family=any
	set firewall.3ginfo_ttl.reload=1
	commit firewall
EOF

uci -q batch << EOF >/dev/null
	delete ucitrack.@3ginfo_ttl[-1]
	add ucitrack 3ginfo_ttl
	set ucitrack.@3ginfo_ttl[-1].init=3ginfo_ttl
	commit ucitrack
EOF

exit 0
